"""empty message

Revision ID: 033e5eddd0c5
Revises: aaf84018c513
Create Date: 2024-11-08 16:19:24.591052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033e5eddd0c5'
down_revision = 'aaf84018c513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=True))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
