"""empty message

Revision ID: 22bcfdc4770c
Revises: e25839fa7c95
Create Date: 2024-07-12 18:25:15.131187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bcfdc4770c'
down_revision = 'e25839fa7c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.alter_column('horario_inicio',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('horario_fim',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.alter_column('horario_fim',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=False)
        batch_op.alter_column('horario_inicio',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
