"""empty message

Revision ID: 4b5a45f0f22f
Revises: 22bcfdc4770c
Create Date: 2024-07-12 18:38:00.704244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5a45f0f22f'
down_revision = '22bcfdc4770c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividade',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nomeAtv', sa.VARCHAR(), nullable=True),
    sa.Column('descricao', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
