"""empty message

Revision ID: 69fea846351b
Revises: 87e6a945d8d7
Create Date: 2024-05-23 11:18:34.968759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fea846351b'
down_revision = '87e6a945d8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turma', sa.String(), nullable=True))
        batch_op.drop_column('mensagem')
        batch_op.drop_column('assunto')
        batch_op.drop_column('respondido')
        batch_op.drop_column('data_envio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_envio', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('respondido', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('assunto', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('mensagem', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('turma')

    # ### end Alembic commands ###
