"""empty message

Revision ID: 8e5f81a10974
Revises: 033e5eddd0c5
Create Date: 2024-11-08 16:38:53.401393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5f81a10974'
down_revision = '033e5eddd0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
        'fk_message_user',  # Nome da constraint
        'user',  # Nome da tabela referenciada
        ['user_id'],  # Coluna na tabela atual
        ['id']  # Coluna na tabela referenciada
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
