"""empty message

Revision ID: cad1e2283da5
Revises: cdce2922f634
Create Date: 2024-07-15 14:43:01.754453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad1e2283da5'
down_revision = 'cdce2922f634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('adm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adm', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
