"""empty message

Revision ID: d15bdefb6944
Revises: 59a7d40e1fe3
Create Date: 2024-07-12 14:42:43.419537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15bdefb6944'
down_revision = '59a7d40e1fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contato')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('turma', sa.VARCHAR(), nullable=True),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('setor')
    # ### end Alembic commands ###
