"""empty message

Revision ID: d6150ce03bdc
Revises: 4b5a45f0f22f
Create Date: 2024-07-15 13:41:07.993222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6150ce03bdc'
down_revision = '4b5a45f0f22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.alter_column('horario_inicio',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('horario_fim',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=False)

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.alter_column('horario_fim',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('horario_inicio',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
