"""empty message

Revision ID: d71279461ccd
Revises: b10bbb5e3412
Create Date: 2024-05-23 11:43:01.194053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71279461ccd'
down_revision = 'b10bbb5e3412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeAtv', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividade')
    # ### end Alembic commands ###
